name: Test
'on':
  push:
    branches:
      - 'master'
  pull_request:
    branches:
      - 'master'

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x, 18.x]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'

      - name: Install node modules and build
        run: |
          yarn install --frozen-lockfile
          yarn run build

      - name: Mocha tests
        shell: bash
        run: |
          yarn run test:mocha:ci

      - name: Coveralls
        if: ${{ matrix.node-version == '18.x' }}
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
        shell: bash
        run: |
          yarn add coveralls -D
          yarn run coveralls
